name: Build & Deploy to Firebase Hosting (React)

on:
  push:
    branches:
      - '**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: --version

      - name: Build Project
        run: npm run build


      - name: Deploy to Firebase Preview Channel
        if: github.event_name == 'pull_request' || contains(github.event.head_commit.message, '[preview]')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:preview
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Production
        if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[preview]')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Comment PR with Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployed! Check it out at your Firebase preview URL.'
            })