name: Build & Deploy to Firebase Hosting (React)

on:
  push:
    branches:
      - '**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Deploying to production..."
            firebase deploy --only hosting:production --token ${{ secrets.FIREBASE_TOKEN }}
          elif contains(github.event.head_commit.message, '[preview]'); then
            echo "Deploying to preview channel..."
            firebase deploy --only hosting:preview --token ${{ secrets.FIREBASE_TOKEN }}
          else
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
            echo "Deploying to preview channel: preview-${BRANCH_NAME}..."
            firebase hosting:channel:deploy preview-${BRANCH_NAME} --token ${{ secrets.FIREBASE_TOKEN }}
          fi